---
layout: single
title: "Vilho James Iipinge"
author_profile: false
---

# Vilho James Iipinge  

**Affiliation:** Harbin Institute of Technology  
**Location:** Shenzhen, Guangdong, China  

📧 [Email](mailto:james943@163.com) |  
💻 [GitHub](https://github.com/jamesvilho) |  
📖 [Google Scholar](https://scholar.google.com/citations?user=XXXXX)
